version: '3.8'
services:
  db:
    image: mysql:8.0.13
    environment:
      MYSQL_DATABASE: usererp
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: dogu4891..00
    ports:
      - "3307:3306"

  app:
    image: usererp-springboot
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/usererp
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: dogu4891..00
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    ports:
      - "8081:8080"
    depends_on:
      - db
      - redis
  redis:
    image: redis
    ports:
      - "6380:6379"
  react:
    image: usererp-react
    ports:
      - "51641:5173"
    depends_on:
      - app